# Site wide configuration
title: "কৃত্রিম বুদ্ধিমত্তা | বাংলা"
description: "ডেটা সায়েন্স এবং কৃত্রিম বুদ্ধিমত্তা নিয়ে আমার ব্লগ।"
logo: 
teaser: 
locale: "bn"
url: "https://shadikulislam.github.io"
baseurl: ""

# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Site owner
owner:
  name: "Shadikul Islam"
  avatar: bio-photo.jpg
  bio: "ডেটা সায়েন্স এবং এআই নিয়ে কাজ করছি।"
  twitter:
